"""Esta es una migracion de bd

Revision ID: a50601c0dba9
Revises: ab46214e3156
Create Date: 2025-11-16 23:26:49.377505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50601c0dba9'
down_revision: Union[str, Sequence[str], None] = 'ab46214e3156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('payment_method_id', sa.Integer(), nullable=False))
    op.add_column('subscription', sa.Column('last_payment_date', sa.Date(), nullable=True))
    op.add_column('subscription', sa.Column('failed_payment_attempts', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscription', 'payment_method', ['payment_method_id'], ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'failed_payment_attempts')
    op.drop_column('subscription', 'last_payment_date')
    op.drop_column('subscription', 'payment_method_id')
    # ### end Alembic commands ###
