"""Migracion a postgres

Revision ID: ab46214e3156
Revises: 
Create Date: 2025-11-16 01:13:49.410132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab46214e3156'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('coupon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('coupon_id'),
    sa.UniqueConstraint('coupon_code')
    )
    op.create_table('loyalty_tier',
    sa.Column('tier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('min_points_required', sa.Integer(), nullable=False),
    sa.Column('points_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('free_shipping_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_coupons_count', sa.Integer(), nullable=False),
    sa.Column('coupon_discount_percentage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tier_id'),
    sa.UniqueConstraint('tier_level')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('physical_activities', sa.JSON(), nullable=False),
    sa.Column('fitness_objectives', sa.JSON(), nullable=False),
    sa.Column('nutritional_value', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.Enum('EMAIL', 'GOOGLE', 'FACEBOOK', name='authtype'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PREFER_NOT_SAY', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('account_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_cognito_sub'), 'user', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_name', sa.String(length=100), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.create_table('fitness_profile',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_fitness_profile_user_id'), 'fitness_profile', ['user_id'], unique=True)
    op.create_table('payment_method',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('PAYPAL', 'CREDIT_CARD', 'DEBIT_CARD', name='paymenttype'), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('expiration_date', sa.String(length=7), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_method_user_id'), 'payment_method', ['user_id'], unique=False)
    op.create_table('product_image',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('shopping_cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_loyalty',
    sa.Column('loyalty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('points_expiration_date', sa.Date(), nullable=True),
    sa.Column('tier_achieved_date', sa.Date(), nullable=False),
    sa.Column('last_points_update', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['loyalty_tier.tier_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loyalty_id')
    )
    op.create_index(op.f('ix_user_loyalty_user_id'), 'user_loyalty', ['user_id'], unique=True)
    op.create_table('cart_item',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_table('subscription',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_delivery_date', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['fitness_profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=True)
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.CheckConstraint('(is_subscription = true AND subscription_id IS NOT NULL) OR (is_subscription = false)', name='check_subscription_order'),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.coupon_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_method.payment_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.subscription_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    op.create_table('point_history',
    sa.Column('point_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loyalty_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('EARNED', 'EXPIRED', name='pointeventtype', native_enum=False), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.CheckConstraint("(event_type = 'earned' AND order_id IS NOT NULL) OR (event_type = 'expired' AND order_id IS NULL)", name='check_order_for_event_type'),
    sa.ForeignKeyConstraint(['loyalty_id'], ['user_loyalty.loyalty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('point_history_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('user_coupon',
    sa.Column('user_coupon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('used_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.coupon_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_coupon_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_user_coupon_user_id'), 'user_coupon', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_coupon_user_id'), table_name='user_coupon')
    op.drop_table('user_coupon')
    op.drop_table('review')
    op.drop_table('point_history')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_user_loyalty_user_id'), table_name='user_loyalty')
    op.drop_table('user_loyalty')
    op.drop_table('shopping_cart')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_payment_method_user_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index(op.f('ix_fitness_profile_user_id'), table_name='fitness_profile')
    op.drop_table('fitness_profile')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cognito_sub'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_table('loyalty_tier')
    op.drop_table('coupon')
    # ### end Alembic commands ###
